-- Rollback espejo de remediation-iam-961.
DELETE FROM rbac.role_feature WHERE feature_id IN (SELECT id FROM rbac_catalog.feature WHERE code IN
  ('SCH_REPORT_VIEW','ENVIRONMENT_REPORT_VIEW','ACT_REPORT_VIEW','DOC_REPORT_VIEW','DOC_TEMPLATE_VIEW','MON_REPORT_VIEW','MON_CATALOG_MANAGE','MON_NOTIFICATION_VIEW'));
DELETE FROM rbac_catalog.feature WHERE code IN
  ('SCH_REPORT_VIEW','ENVIRONMENT_REPORT_VIEW','ACT_REPORT_VIEW','DOC_REPORT_VIEW','DOC_TEMPLATE_VIEW','MON_REPORT_VIEW','MON_CATALOG_MANAGE','MON_NOTIFICATION_VIEW');
