-- R3.1 remediación RBAC (2026-08-07). Changeset NUEVO (remediation-iam-961).
-- Agrega las 8 features que el contrato OpenAPI exige (x-required-feature) y el seed no tenía.
-- INSERT idempotente (ON CONFLICT DO NOTHING); NO modifica el seed aplicado.
INSERT INTO rbac_catalog.feature (module_id, code, name, action_level)
SELECT m.id, v.code, v.name, v.action FROM (VALUES
  ('MOD_SCHEDULING','SCH_REPORT_VIEW','Ver reportes de horarios','READ'),
  ('MOD_ENVIRONMENT','ENVIRONMENT_REPORT_VIEW','Ver reportes de ambientes','READ'),
  ('MOD_ACTORS','ACT_REPORT_VIEW','Ver reportes de actores','READ'),
  ('MOD_DOCUMENTS','DOC_REPORT_VIEW','Ver reportes de documentos','READ'),
  ('MOD_DOCUMENTS','DOC_TEMPLATE_VIEW','Ver plantillas de documento','READ'),
  ('MOD_MONITORING','MON_REPORT_VIEW','Ver reportes de monitoreo','READ'),
  ('MOD_MONITORING','MON_CATALOG_MANAGE','Gestionar catalogos de monitoreo','WRITE'),
  ('MOD_MONITORING','MON_NOTIFICATION_VIEW','Ver notificaciones','READ')
) AS v(mod_code, code, name, action)
JOIN rbac_catalog.module m ON m.code = v.mod_code
ON CONFLICT (code) DO NOTHING;

INSERT INTO rbac.role_feature (role_id, feature_id, scope_type)
SELECT r.id, f.id, v.scope FROM (VALUES
  ('SYSTEM_ADMIN','SCH_REPORT_VIEW','GLOBAL'),('CENTER_DIRECTOR','SCH_REPORT_VIEW','TRAINING_CENTER'),('COORDINATOR','SCH_REPORT_VIEW','TRAINING_CENTER'),
  ('SYSTEM_ADMIN','ENVIRONMENT_REPORT_VIEW','GLOBAL'),('CENTER_DIRECTOR','ENVIRONMENT_REPORT_VIEW','TRAINING_CENTER'),('COORDINATOR','ENVIRONMENT_REPORT_VIEW','TRAINING_CENTER'),
  ('SYSTEM_ADMIN','ACT_REPORT_VIEW','GLOBAL'),('CENTER_DIRECTOR','ACT_REPORT_VIEW','TRAINING_CENTER'),('COORDINATOR','ACT_REPORT_VIEW','TRAINING_CENTER'),
  ('SYSTEM_ADMIN','MON_REPORT_VIEW','GLOBAL'),('CENTER_DIRECTOR','MON_REPORT_VIEW','TRAINING_CENTER'),('COORDINATOR','MON_REPORT_VIEW','TRAINING_CENTER'),
  ('SYSTEM_ADMIN','DOC_REPORT_VIEW','GLOBAL'),('CENTER_DIRECTOR','DOC_REPORT_VIEW','TRAINING_CENTER'),('ADMIN_STAFF','DOC_REPORT_VIEW','GLOBAL'),
  ('SYSTEM_ADMIN','DOC_TEMPLATE_VIEW','GLOBAL'),('ADMIN_STAFF','DOC_TEMPLATE_VIEW','GLOBAL'),
  ('SYSTEM_ADMIN','MON_CATALOG_MANAGE','GLOBAL'),('ADMIN_STAFF','MON_CATALOG_MANAGE','GLOBAL'),
  ('SYSTEM_ADMIN','MON_NOTIFICATION_VIEW','GLOBAL'),('CENTER_DIRECTOR','MON_NOTIFICATION_VIEW','TRAINING_CENTER'),('COORDINATOR','MON_NOTIFICATION_VIEW','TRAINING_CENTER'),('INSTRUCTOR','MON_NOTIFICATION_VIEW','OWN_FICHAS'),('LEARNER','MON_NOTIFICATION_VIEW','OWN_FICHA_AS_LEARNER'),('ADMIN_STAFF','MON_NOTIFICATION_VIEW','GLOBAL')
) AS v(role_name, feature_code, scope)
JOIN rbac.role r ON r.name = v.role_name
JOIN rbac_catalog.feature f ON f.code = v.feature_code
ON CONFLICT DO NOTHING;
